"""
Daily Report Generator - Creates and delivers market monitoring reports.

Formats analysis results into readable reports and delivers via
configured channels (email, Telegram, Slack).
"""

import csv
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from market_agent.price_analysis import MarketStats

logger = logging.getLogger(__name__)


class DailyReportGenerator:
    """Generates daily market monitoring reports."""

    def __init__(self, output_dir: str = "reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, analysis: dict) -> str:
        """
        Generate a daily report from analysis results.

        Args:
            analysis: Dict from PriceAnalyzer.analyze()

        Returns:
            Formatted report as a string
        """
        stats: MarketStats = analysis.get("stats", MarketStats())
        trends: dict = analysis.get("trends", {})

        date_str = datetime.now().strftime("%Y-%m-%d")
        lines = [
            f"📋 Daily Market Report — {date_str}",
            "=" * 45,
            "",
            f"📊 Market Overview ({stats.count} listings)",
            f"  Median Price: ${stats.median_price:.0f}",
            f"  Mean Price:   ${stats.mean_price:.0f}",
            f"  Price Range:  ${stats.min_price:.0f} - ${stats.max_price:.0f}",
            f"  Std Dev:      ${stats.stdev_price:.0f}",
        ]

        if stats.avg_rating:
            lines.append(f"  Avg Rating:   {stats.avg_rating:.1f} ⭐")

        if stats.by_bedrooms:
            lines.append("")
            lines.append("🏠 Price by Bedroom Count")
            for bedrooms, price in sorted(stats.by_bedrooms.items()):
                lines.append(f"  {bedrooms}BR: ${price:.0f}")

        if stats.by_neighborhood:
            lines.append("")
            lines.append("📍 Price by Neighborhood")
            for hood, price in sorted(stats.by_neighborhood.items(), key=lambda x: x[1]):
                lines.append(f"  {hood}: ${price:.0f}")

        if trends:
            lines.append("")
            lines.append("📈 Market Trends")
            for key, val in trends.items():
                label = key.replace("_", " ").title()
                lines.append(f"  {label}: {val}")

        lines.append("")
        lines.append("=" * 45)
        lines.append("Generated by Airbnb AI Agent")

        report = "\n".join(lines)

        # Save to file
        filename = f"market_report_{date_str}.txt"
        filepath = self.output_dir / filename
        filepath.write_text(report)
        logger.info(f"Report saved to {filepath}")

        # Also append to CSV history
        self._append_csv(stats, date_str)

        return report

    def _append_csv(self, stats: MarketStats, date_str: str) -> None:
        """Append daily stats to CSV history."""
        csv_path = Path("data/market_history.csv")
        write_header = not csv_path.exists()

        with open(csv_path, "a", newline="") as f:
            writer = csv.writer(f)
            if write_header:
                writer.writerow([
                    "date", "count", "median_price", "mean_price",
                    "min_price", "max_price", "avg_rating",
                ])
            writer.writerow([
                date_str, stats.count,
                stats.median_price, stats.mean_price,
                stats.min_price, stats.max_price,
                stats.avg_rating or "",
            ])

    async def send_email(self, report: str, recipient: str = "") -> bool:
        """Send report via email."""
        # TODO: Implement email delivery
        logger.info(f"Email delivery not yet implemented (would send to {recipient})")
        return False

    async def send_telegram(self, report: str, chat_id: str = "") -> bool:
        """Send report via Telegram."""
        # TODO: Implement Telegram delivery
        logger.info(f"Telegram delivery not yet implemented (would send to {chat_id})")
        return False
